---
# Variables for DB SERVERS
###################################################
###   MYSQL
###################################################
mysql_port: "{{ sweagle_mysql_port }}"
# MySQL root user and password
mysql_root_user: root
mysql_root_password: sweagle3.MYSQL
mysql_root_password_update: "{{ sweagle_mysql_password_update|default(true) }}"

# not yet supported
#mysql_data_dir: "/opt/mysql/data"
#mysql_log_dir: "/opt/mysql/log"


###################################################
###   MONGODB
###################################################
mongodb_version: "3.6"

mongodb_net_bindip: 127.0.0.1                    # Comma separated list of ip addresses to listen on
mongodb_net_port: "{{ sweagle_mongo_port }}"
mongodb_security_authorization: "disabled"

mongodb_storage_dbpath: "/opt/mongodb/data"
mongodb_systemlog_path: "/opt/mongodb/log/{{ mongodb_daemon_name }}.log"   # Log file to send write to instead of stdout

mongodb_user_admin_name: sweagle
mongodb_user_admin_password: sweagle

mongodb_root_admin_name: root_user
mongodb_root_admin_password: root_password
