---
- name: Install unzip from repo
  package:
    name: unzip
    state: present
  become: true
  when: not force_local_installation
  tags: [ nginx, sweagle, sweagle-web ]

- name: Install unzip from local
  package:
    name: "{{ item }}"
    update_cache: yes
  become: true
  with_fileglob:
    - "../../../files/{{ ansible_os_family }}/*unzip*.{{ 'deb' if (ansible_os_family == 'Debian') else 'rpm' }}"
  when: force_local_installation
  tags: [ nginx, sweagle, sweagle-web ]

- name: "Check if SWEAGLE package is in {{ playbook_dir }}/files/sweagle"
  stat:
    path: "{{ playbook_dir }}/files/sweagle/full-{{ sweagle_version}}.zip"
  register: sweagleFile
  tags: [ nginx, sweagle, sweagle-web ]

- name: Unzip package "full-{{ sweagle_version }}.zip from local
  unarchive:
    src: "../../../files/sweagle/full-{{ sweagle_version}}.zip"
    dest: /tmp
  when: sweagleFile.stat.exists
  tags: [ nginx, sweagle, sweagle-web ]

- name: Unzip package "full-{{ sweagle_version }}.zip"
  unarchive:
    src: "../../sweagle/files/full-{{ sweagle_version}}.zip"
    dest: /tmp
  when: not sweagleFile.stat.exists
  tags: [ nginx, sweagle, sweagle-web ]
