---
# Install NGINX
- name: Check if nginx repository is present
  shell: rpm -qa | grep nginx-release
  register: nginx_repo
  ignore_errors: True
  when: not force_local_installation and ansible_os_family == 'RedHat'
  tags: nginx

- name: Add repository nginx-release (CentOS6/CentOS7)
  yum: name="http://nginx.org/packages/centos/{{ansible_distribution_major_version}}/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm"
  when: nginx_repo|failed
  tags: nginx

- name: Install nginx from repo
  package:
    name: nginx
    state: present
  become: true
  become_user: root
  when: not force_local_installation
  tags: nginx

- name: Install nginx from local
  package:
    name: "{{ item }}"
    state: present
  become: true
  become_user: root
  with_fileglob:
    - "../../../files/{{ ansible_os_family }}/nginx/*nginx*.{{ 'deb' if (ansible_os_family == 'Debian') else 'rpm' }}"
  when: force_local_installation
  tags: nginx

- name: Touch access.log file
  file:
    path: "/var/log/nginx/acces.log"
    state: touch
  become: true
  tags: nginx

- name: Configure web site
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true
  tags: nginx
  notify: Restart nginx

- name: Deploy SWEAGLE zip
  include_tasks: deploy-sweagle-zip.yml
  tags: [ nginx, sweagle, sweagle-web ]

- name: Configure SWEAGLE website
  include_tasks: configure-sweagle.yml
  tags: [ nginx, sweagle, sweagle-web ]
