---
# Install NGINX
- name: Install nginx
  package:
    name: nginx
    state: present
  become: true
  become_user: root
  tags: nginx

- name: Touch access.log file
  file:
    path: "/var/log/nginx/acces.log"
    state: touch

- name: Check nginx service is running
  service:
    name: nginx
    enabled: yes
    state: started
  become: true
  become_user: root
  tags: nginx
