---
# Install NGINX
- name: Install nginx from repo
  package:
    name: nginx
    state: present
  become: true
  become_user: root
  when: not force_local_installation
  tags: nginx

- name: Install nginx from local
  package:
    name: "{{ item }}"
    state: present
  become: true
  become_user: root
  with_fileglob:
    - "../../../files/nginx/*nginx*.{{ 'deb' if (ansible_os_family == 'Debian') else 'rpm' }}"
  when: force_local_installation
  tags: nginx

- name: Touch access.log file
  file:
    path: "/var/log/nginx/acces.log"
    state: touch
  become: true
  tags: nginx

- name: Configure web site
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true
  tags: nginx

- name: Check nginx service is running
  service:
    name: nginx
    enabled: yes
    state: restarted
  become: true
  become_user: root
  tags: nginx
