- name: Start MongoDB Server
  systemd:
    name: mongod
    state: started

- name: Check SWEAGLE user exists
  shell: mongo {{ mongodb_user }} --eval 'db.getUsers()'
  register: mongo_users

- name: Extract user
  shell: echo "{{ mongo_users.stdout }}" | grep "{{ mongodb_user }}"."{{ sweagle_mongo_user }}"
  register: user_output
  ignore_errors: true

- name: Create MongoDB SWEAGLE Databases
  shell: mongo --eval 'db.getSiblingDB("{{ item }}")'
  with_items:
    - sweagle
    - admin
  when: user_output.rc != 0

- name: Create MongoDB SWEAGLE Users
  shell: mongo {{ mongodb_user }} --eval 'printjson(db.createUser({ user:"{{ sweagle_mongo_user }}", pwd:"{{ sweagle_mongo_password }}", roles:[{ role:"readWrite", db:"{{ mongodb_user }}"}]}))'
  when: user_output.rc != 0
