---
# Set the system settings for mongo
- name: create mongodb system group
  group:
    name: "{{ mongodb_user }}"
    state: present
  tags: mongodb

- name: create mongodb system user
  user:
    name: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    state: present
  tags: mongodb

# Workaround because default(omit) is not working. At least in Ansible 2.8.

- name: set mongodb gid
  group:
    name: "{{ mongodb_user }}"
    gid: "{{ mongodb_gid }}"
    state: present
  when: mongodb_gid is defined
  tags: mongodb

- name: set mongodb uid
  user:
    name: "{{ mongodb_user }}"
    uid: "{{ mongodb_uid }}"
    group: "{{ mongodb_user }}"
    state: present
  when: mongodb_uid is defined
  tags: mongodb

- name: Create keyFile
  copy:
    dest: "{{ mongodb_security_keyfile }}"
    content: "{{ mongodb_keyfile_content }}"
    owner: "{{ mongodb_user }}"
    group: "root"
    mode: 0600
  when: mongodb_replication_replset | length > 0
  tags: mongodb

- name: Create log dir if missing
  file:
    state: directory
    recurse: true
    dest: "{{ mongodb_systemlog_path|dirname }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: 0755
  become: true
  become_user: root
  when: mongodb_systemlog_destination == "file"
  tags: mongodb

- name: Check that logfile exists
  stat: path={{ mongodb_systemlog_path }}
  register: logfile_stat
  when: mongodb_systemlog_destination == "file"
  tags: mongodb

- name: Create log if missing
  file:
    state: touch
    dest: "{{ mongodb_systemlog_path }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: 0755
  become: true
  when: ( mongodb_systemlog_destination == "file"
        and logfile_stat is defined
        and not logfile_stat.stat.exists )
  tags: mongodb

- name: Ensure dbpath directory
  file:
    path: "{{ mongodb_storage_dbpath }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    setype: 'mongod_var_lib_t'
    recurse: true
    follow: true
  become: true
  become_user: root
  tags: mongodb

- name: apply selinux policy if active
  include_tasks: "configure-selinux.yml"
  when: ansible_selinux.status != 'disabled'
  tags: mongodb

- name: Configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  notify:
    - mongodb restart
    - service started
    - wait when mongodb is started
  tags: mongodb

- name: Flush all handlers at this point
  meta: flush_handlers
  tags: mongodb
