---
- name: Create disable transparent hugepages systemd service file
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/disable-transparent-hugepages.service
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - "disable-transparent-hugepages.{{ ansible_distribution | lower }}.service"
    - "disable-transparent-hugepages.{{ ansible_os_family | lower }}.service"
  tags: mongodb

- name: Enable disable-transparent-hugepages.service
  systemd:
    name: disable-transparent-hugepages
    daemon-reload: true
    enabled: true
    state: started
  tags: mongodb
