---
## Prerequisite
## be sure ansible.cfg knows your inventory folder
# more /etc/ansible/ansible.cfg
## Test with
# ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --check
- hosts: all
  roles:
    - jdk

- hosts: dbservers
  roles:
    - mysql
    - mongodb
    - elasticsearch
    - vault

- hosts: webservers
  roles:
    - nginx
