---
## Prerequisites:
## Packages Ansible 2.5 or higher + package sshpass
## be sure ansible.cfg knows your inventory folder and authorize non ssh checks
# more /etc/ansible/ansible.cfg

## WARNING
## Copy your SWEAGLE full package zip file to /roles/sweagle/files
## Copy your SWEAGLE license in parameter sweagle_license_key to /inventories/all-in-one/group_vars

## Test with
# ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --check
##
## To run only for some components use
#ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "<COMPONENT>"
#ex to do only mySQL: ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "mysql"
#ex to do only sweagle: ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "sweagle"

- hosts: all
  roles:
    - system

- hosts: dbservers
  roles:
    - mysql
    - mongodb
## Check mongo connection
# mongo -u staticTreeUser -p staticTreePassword localhost:27017/sweagle

- hosts: indexservers
  roles:
    - elasticsearch
## Start elastic search manually to checks
#

## Nginx must be installed before SWEAGLE
## So that web package could be unpack directly to nginx after
- hosts: webservers
  roles:
    - nginx

- hosts: appservers, webservers
  roles:
    - jdk
    - vault
    - sweagle
## check sweagle working, start non interactive
#cd /opt/SWEAGLE/scripts
#./startCORE.sh
