---
## Prerequisite
## be sure ansible.cfg knows your inventory folder and authorize non ssh checks
# more /etc/ansible/ansible.cfg
## Test with
# ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --check
- hosts: all
  roles:
    - system

- hosts: dbservers
  roles:
    - mysql
    - mongodb

- hosts: indexservers
  roles:
    - elasticsearch

- hosts: appservers
  roles:
    - jdk
    - vault
    - sweagle-core


- hosts: webservers
  roles:
    - nginx
