---
## Prerequisite
## be sure ansible.cfg knows your inventory folder and authorize non ssh checks
# more /etc/ansible/ansible.cfg
## Test with
# ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --check
##
## To run only for some components use
#ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "<COMPONENT>"
#ex to do only mySQL: ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "mysql"
#ex to do only sweagle: ansible-playbook all-in-one-install.yml -i ./inventories/all-in-one/hosts.yml --tags "sweagle"

- hosts: all
  roles:
    - system

- hosts: dbservers
  roles:
    - mysql
    - mongodb
## check mongo connection
#mongo -u staticTreeUser -p staticTreePassword localhost:27017/sweagle



- hosts: indexservers
  roles:
    - elasticsearch

- hosts: appservers
  roles:
    - jdk
    - vault
    - sweagle

- hosts: webservers
  roles:
    - nginx
