---
## Prerequisites:
## Packages Ansible 2.5 or higher + package sshpass
## be sure ansible.cfg knows your inventory folder and authorize non ssh checks
# more /etc/ansible/ansible.cfg

## WARNING
## Copy your SWEAGLE full package zip file to /roles/sweagle/files
## Copy your SWEAGLE license in parameter sweagle_license_key to /inventories/all-in-one/group_vars

## Test with
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml --check

## For full installation (including prerequisites)
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml
## For localhost installation, in case of host unreachable, use
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml --connection local


## For SWEAGLE installation (prerequisites already installed)
## (check before that prerequisites are well installed)
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml--tags sweagle

## To install only a specifif component or prerequisite
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml --tags "<COMPONENT>"
## Example to do only mySQL:
# ansible-playbook all-install.yml -i ./inventories/all-in-one/hosts.yml --tags mysql

- hosts: all
  roles:
    - system

- hosts: dbservers
  roles:
    - mysql
## Check mysql connection
# mysql -u mdm_user -pmdm_password
# use mdm
## => you should get connected to mdm database
    - mongodb
## Check mongo connection
# mongo -u staticTreeUser -p staticTreePassword localhost:27017/sweagle
## => you should get user connected to mongo

- hosts: indexservers
  roles:
    - elasticsearch
## Start elastic search manually to checks
#

## Nginx must be installed before SWEAGLE
## So that web package could be unpack directly to nginx after
- hosts: webservers
  roles:
    - nginx
## test with:
# curl http://127.0.0.1
## => you should the nginx default page

- hosts: appservers, webservers
  roles:
    - jdk
    - vault
    - sweagle
## check sweagle working, start non interactive
#cd /opt/SWEAGLE/scripts
#./startCORE.sh

## test with:
# curl http://127.0.0.1
## => you should get the sweagle login page
