---
## All vars used by this role
sweagle_system_user: sweagle
sweagle_system_group: sweagle

sweagle_version:
sweagle_installation_folder: /opt/sweagle
sweagle_create_services: true
sweagle_license_key:

sweagle_service_name: sweagle
sweagle_heap: 512m
sweagle_tenant: poc

sweagle_core_port: 8081
sweagle_taskrunner_port: 8082
sweagle_scriptexecutor_port: 8084
sweagle_ml_port: 8083

sweagle_core_xmx: "4000m"
sweagle_taskrunner_xmx: "1000m"
sweagle_scriptexecutor_xmx: "2000m"
sweagle_ml_xmx: "2000m"
