---
- name: disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system

- name: install screen, jq and telnet on Debian family from repo
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - jq
  become: true
  when: ansible_os_family == 'Debian' and not force_local_installation
  tags: system

- name: install screen, jq and telnet on Red Hat family from repo
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - epel-release
    - jq
  become: true
  when: ansible_os_family == 'RedHat' and not force_local_installation
  tags: system

- name: install screen, jq and telnet on Debian family from local
  package:
    pkg: "{{ item }}"
    state: present
  with_items: "{% if ansible_os_family == 'Debian' %}{{ lookup('fileglob', '../../../files/*.deb').split(',') | sort }}
    {% else %}{{ lookup('fileglob', '../../../files/*.rpm').split(',') | sort }}{% endif %}"
  become: true
  when: force_local_installation
  tags: system

- name: disable selinux at runtime
  shell: setenforce 0
  become: true
  when: ansible_selinux.status != 'disabled'
  tags: system

- name: disable selinux permanently
  selinux:
    state: disabled
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system
