---
- name: disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system

- name: install screen, jq and telnet on Debian family
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - jq
  become: true
  when: ansible_os_family == 'Debian'
  tags: system

- name: install screen, jq and telnet on Red Hat family
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - screen
    - telnet
    - epel-release
    - jq
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system

- name: disable selinux at runtime
  shell: setenforce 0
  become: true
  when: ansible_selinux.status != 'disabled'
  tags: system

- name: disable selinux permanently
  selinux:
    state: disabled
  become: true
  when: ansible_os_family == 'RedHat'
  tags: system
