---
- name: Get Vault token
  set_fact: sweagle_vault_token="{{ vault_token }}"
  when: sweagle_vault_token == "" and vault_token != ""
  tags: [ sweagle, sweagle-core, sweagle-vault ]

- debug: msg="{{ sweagle_license_key }}"
  tags: always

- pause:
    prompt: "Please paste your license key:"
    echo: true
  register: sweagle_license_key
  when: sweagle_license_key == ""
  tags: [ sweagle, sweagle-core ]

- debug: msg="{{ sweagle_license_key }}"
  tags: always

- name: Configure core application.yml
  template:
    src: "{{ sweagle_version }}/core-application.yml.j2"
    dest: "{{ sweagle_installation_folder }}/bin/core/application.yml"
  tags: [ sweagle, sweagle-core ]

- name: Create service core
  shell: "{{ sweagle_installation_folder }}/scripts/createService.sh sweagleCore {{ sweagle_installation_folder }}/bin/core core-{{ sweagle_version }}.jar {{ sweagle_core_xmx }}"
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-core ]

- name: Enable and start core service
  service:
    name: "sweagleCore"
    state: started
    enabled: yes
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-core ]

- name: Wait for core to startup
  wait_for: host=localhost port={{ sweagle_core_port }} delay=15 connect_timeout=5 timeout=120
  when: sweagle_create_services
  tags: [ sweagle, sweagle-core ]
