---
- name: Configure scriptexecutor application.yml
  template:
    src: "{{ sweagle_version }}/scriptexecutor-application.yml.j2"
    dest: "{{ sweagle_installation_folder }}/bin/scriptExecutor/application.yml"
  tags: [ sweagle, sweagle-scriptexecutor ]

- name: Create service scriptexecutor
  shell: "{{ sweagle_installation_folder }}/scripts/createService.sh sweagleScriptExecutor {{ sweagle_installation_folder }}/bin/scriptExecutor script-executor-{{ sweagle_version }}.jar {{ sweagle_scriptexecutor_xmx }}"
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-scriptexecutor ]

- name: Enable and start scriptexecutor service
  service:
    name: "sweagleScriptExecutor"
    state: started
    enabled: yes
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-scriptexecutor ]

- name: Wait for scriptexecutor to startup
  wait_for: host="{{ inventory_hostname }}" port={{ sweagle_scriptexecutor_port }} delay=15 connect_timeout=5 timeout=60
  when: sweagle_create_services
  tags: [ sweagle, sweagle-scriptexecutor ]
