---
## This applies sonly to webservers
- name: Create SWEAGLE web root
  file:
    path: "{{ sweagle_web_root_dir }}"
    state: directory
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Unzip web package
  unarchive:
    src: "/tmp/{{ sweagle_version }}/full/bin/ui/dist.zip"
    dest: "{{ sweagle_web_root_dir }}"
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Configure web site
  template:
    src: "{{ sweagle_version }}/default.j2"
    dest: "/etc/nginx/conf.d/default"
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Configure sweagle.conf
  template:
    src: "sweagle.conf"
    dest: "/etc/nginx/conf.d/sweagle.conf"
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Configure nginx.conf
  template:
    src: "{{ sweagle_version }}/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  become: true
  notify:
     - Restart nginx
  tags: [ sweagle, sweagle-web ]
