---
## This applies sonly to webservers
- name: Create SWEAGLE web root
  file:
    path: "/usr/share/nginx/html/sweagle"
    state: directory
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Unzip web package
  unarchive:
    src: "/tmp/{{ sweagle_version }}/full/bin/ui/dist.zip"
    dest: "{{ sweagle_web_root_dir }}"
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Configure web sites available
  template:
    src: "{{ sweagle_version }}/sites-available/default.j2"
    dest: "/etc/nginx/sites-available/default"
  become: true
  tags: [ sweagle, sweagle-web ]

- name: Reconfigure nginx.conf
  template:
    src: "{{ sweagle_version }}/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  become: true
  notify:
     - Restart nginx
  tags: [ sweagle, sweagle-web ]
