---

- name: Unzip package "full_{{ sweagle_version }}.zip"
  unarchive:
    src: "full_{{ sweagle_version}}.zip"
    dest: /tmp
  tags: [ sweagle, sweagle-core, sweagle-web ]

- name: Configure SWEAGLE web site
  include_tasks: configure-sweagle-web.yml
  hosts: webservers
  tags: [ sweagle, sweagle-web ]

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: true
  become_user: root
  tags: [ sweagle, sweagle-core, system ]
  ignore_errors: true

#- name: Allow 'wheel' group to have passwordless sudo
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^%wheel'
#    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: 'visudo -cf %s'
#  become: true
#  become_user: root
#  tags: [ sweagle-core, sweagle, system ]

- name: Create SWEAGLE system group
  group:
    name: "{{ sweagle_system_group }}"
    state: present
  become: true
  tags: [ sweagle, sweagle-core, system ]

- name: Create SWEAGLE user "{{sweagle_system_user }}"
  user:
    name: "{{sweagle_system_user }}"
    state: present
    groups: "wheel,{{ sweagle_system_group }},sudo"
    system: yes
  become: true
  become_user: root
  tags: [ sweagle, sweagle-core, system ]

- name: Create installation folder "{{ sweagle_installation_folder }}"
  file:
    path: "{{ sweagle_installation_folder }}"
    state: directory
    owner: "{{ sweagle_system_user }}"
    group: "{{ sweagle_system_group }}"
    mode: 0775
  become: true
  tags: [ sweagle, sweagle-core, system ]

- name: copy content to installation folder
  synchronize:
    src: "/tmp/{{ sweagle_version }}/full/"
    dest: "{{ sweagle_installation_folder }}"
  delegate_to: "{{ inventory_hostname }}"
  tags: [ sweagle, sweagle-core ]

- name: set correct version in "{{ sweagle_installation_folder }}/appRelease.settings"
  replace:
    path: "{{ sweagle_installation_folder }}/scripts/config/appRelease.settings"
    regexp: '\d+\.\d+\.\d+'
    replace: "{{ sweagle_version }}"
  tags: [ sweagle, sweagle-core ]

- name: make shell scripts in "{{ sweagle_installation_folder }}/scripts" executable
  file:
    dest: "{{ sweagle_installation_folder }}/scripts"
    mode: a+x
  tags: [ sweagle, sweagle-core ]
#- name: make shell scripts in "{{ sweagle_installation_folder }}/scripts" executable
#  shell: "chmod +x {{sweagle_installation_folder }}/scripts/*.sh"
#  tags: [ sweagle-core, sweagle ]

- name: set ownership in "{{ sweagle_installation_folder }}"
  file:
    dest: "{{ sweagle_installation_folder }}"
    owner: "{{ sweagle_system_user }}"
    group: "{{ sweagle_system_group }}"
    recurse: yes
  become: true
  tags: [ sweagle, sweagle-core ]

- name: configure core appConfig.settings
  template:
    src: "{{ sweagle_version }}/appConfig.settings.j2"
    dest: "{{ sweagle_installation_folder }}/scripts/config/appConfig.settings"
  tags: [ sweagle-core, sweagle ]

- name: Configure scriptexecutor
  include_tasks: configure-sweagle-scriptexecutor.yml
  hosts: appservers
  tags: [ sweagle, sweagle-scriptexecutor ]

- name: Configure core
  include_tasks: configure-sweagle-core.yml
  hosts: appservers
  tags: [ sweagle, sweagle-core ]

- name: Configure taskrunner
  include_tasks: configure-sweagle-taskrunner.yml
  hosts: appservers
  tags: [ sweagle, sweagle-taskrunner ]

- name: Configure prepare tenant script
  template:
    src: "{{ sweagle_version }}/prepareTenantNew.sh.j2"
    dest: "{{ sweagle_installation_folder }}/scripts/prepareTenantNew.sh"
  tags: [ sweagle-core, sweagle ]

- name: Execute prepare tenant script
  shell: "{{ sweagle_installation_folder }}/scripts/prepareTenantNew.sh {{ sweagle_tenant }}"
  tags: [ sweagle, sweagle-core ]


#  shell: "chmod +x {{sweagle_installation_folder }}/scripts/*.sh"
#  tags: [ sweagle-core, sweagle ]
