---
- name: Deploy SWEAGLE zip
  include_tasks: deploy-sweagle-zip.yml
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]

- name: Make sure we have a sudo or wheel group
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - sudo
  become: true
  become_user: root
  ignore_errors: true
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core, systemf ]

#- name: Allow 'wheel' group to have passwordless sudo
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^%wheel'
#    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: 'visudo -cf %s'
#  become: true
#  become_user: root
#  tags: [ sweagle-core, sweagle, system ]

- name: Create SWEAGLE system group
  group:
    name: "{{ sweagle_system_group }}"
    state: present
  become: true
  tags: [ sweagle, sweagle-core, system ]

- name: Create SWEAGLE user "{{sweagle_system_user }}"
  user:
    name: "{{sweagle_system_user }}"
    state: present
    groups: "wheel,{{ sweagle_system_group }},sudo"
    system: yes
  become: true
  become_user: root
  tags: [ sweagle, sweagle-core, system ]

- name: Create installation folder "{{ sweagle_installation_folder }}"
  file:
    path: "{{ sweagle_installation_folder }}/scripts"
    state: directory
    owner: "{{ sweagle_system_user }}"
    group: "{{ sweagle_system_group }}"
    mode: 0775
  become: true
  tags: [ sweagle, sweagle-core ]

- name: Copy content to installation folder
  synchronize:
    src: "/tmp/{{ sweagle_version }}/full/"
    dest: "{{ sweagle_installation_folder }}"
  delegate_to: "{{ inventory_hostname }}"
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]

- name: Set ownership in "{{ sweagle_installation_folder }}"
  file:
    dest: "{{ sweagle_installation_folder }}"
    owner: "{{ sweagle_system_user }}"
    group: "{{ sweagle_system_group }}"
    recurse: yes
  become: true
  tags: [ sweagle, sweagle-core ]

- name: Set correct version in "{{ sweagle_installation_folder }}/appRelease.settings"
  replace:
    path: "{{ sweagle_installation_folder }}/scripts/config/appRelease.settings"
    regexp: '\d+\.\d+\.\d+'
    replace: "{{ sweagle_version }}"
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]

- name: Make shell scripts in "{{ sweagle_installation_folder }}/scripts" executable
  file:
    dest: "{{ sweagle_installation_folder }}/scripts"
    mode: a+x
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]
#- name: make shell scripts in "{{ sweagle_installation_folder }}/scripts" executable
#  shell: "chmod +x {{sweagle_installation_folder }}/scripts/*.sh"
#  tags: [ sweagle-core, sweagle ]

- name: Configure appConfig.settings
  template:
    src: "{{ sweagle_version }}/appConfig.settings.j2"
    dest: "{{ sweagle_installation_folder }}/scripts/config/appConfig.settings"
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]

- name: Configure scriptexecutor
  include_tasks: configure-sweagle-scriptexecutor.yml
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-scriptexecutor ]

- name: Configure core
  include_tasks: configure-sweagle-core.yml
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-core ]

- name: Configure taskrunner
  include_tasks: configure-sweagle-taskrunner.yml
  when: inventory_hostname in groups['appservers']
  tags: [ sweagle, sweagle-taskrunner ]
