---
# Install MYSQL
- name: Install MySQL packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - mysql-common
    - python-mysqldb
  become: true
  become_user: root
  tags: mysql

- name: Configure MySQL
  template:
    src: "my.cnf.j2"
    dest: "{{ mysql_config_dir }}/my.cnf"
    mode: preserve
  become: true
  become_user: root
  notify: "Restart mysql"
  tags: mysql

- name: Check mysql service is running
  service:
    name: mysql
    enabled: yes
    state: started
  tags: mysql

- name: Include SWEAGLE configuration.yml
  include: configure-sweagle.yml
  tags: mysql
