---
# Install MYSQL
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags: [mysql, sweagle, sweagle-mysql]

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 3
  tags: always

- name: Install the MySQL repo for Red Hat
  yum:
    name: "{{ mysql_repository }}"
    state: present
  when: ansible_os_family == "RedHat"
  tags: mysql

- name: Install MySQL packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_packages }}"
  become: true
  become_user: root
  tags: mysql

- name: Check mysql service is running
  service:
    name: "{{ mysql_daemon }}"
    enabled: yes
    state: started
  tags: mysql

- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false
  tags: mysql

# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
    mysql -u {{ mysql_root_user }} -NBe
    'ALTER USER "{{ mysql_root_user }}"@localhost
    IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  become: true
  become_user: root
  when: mysql_root_password_update
    and ('5.7.' in mysql_cli_version.stdout or '8.0.' in mysql_cli_version.stdout)
    and ansible_os_family == "Debian"
  tags: mysql

# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  shell: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mysql_root_user }}"@localhost = PASSWORD("{{ mysql_root_password }}");'
  become: true
  become_user: root
  when: mysql_root_password_update
    and ('5.7.' not in mysql_cli_version.stdout and '8.0.' not in mysql_cli_version.stdout)
    and ansible_os_family == "Debian"
  tags: mysql

- name: Find temporary root password for Red Hat
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_root_password_temp
  when: mysql_root_password_update and ansible_os_family == "RedHat"
  tags: mysql

- debug:
    msg: "{{ mysql_root_password_temp.stdout }}"
  when: mysql_root_password_update and ansible_os_family == "RedHat"
  tags: mysql

- name: Set new root password for Red Hat
  shell: >
    mysql -u {{ mysql_root_user }}  -p{{ mysql_root_password_temp.stdout }} --connect-expired-password -e
    'SET PASSWORD = PASSWORD("{{ mysql_root_password }}");'
# OR
#    mysql -u {{ mysql_root_user }} -p{{ mysql_root_password_temp.stdout }} --connect-expired-password -e
#    'ALTER USER "{{ mysql_root_user }}"@localhost
#    IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  become: true
  become_user: root
  when: mysql_root_password_update and ansible_os_family == "RedHat"
  tags: mysql

# Has to be after the password assignment, for idempotency.
#- name: Configure MySQL
#  template:
#    src: "my.cnf.j2"
#    dest: "{{ mysql_config_dir }}/my.cnf"
#    mode: preserve
#  become: true
#  become_user: root
#  tags: mysql

- name: Restart mysql to take into account new configuration
  service:
    name: "{{ mysql_daemon }}"
    state: restarted
  become: true
  become_user: root
  tags: mysql

- name: Include SWEAGLE configuration.yml
  include_tasks: configure-sweagle.yml
  tags: [ mysql, sweagle, sweagle-mysql ]
