---
# Install MYSQL
- name: Install the MySQL repo for Red Hat
  package:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"
  tags: mysql

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags: [mysql, sweagle, sweagle-mysql]

- name: Install MySQL packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_packages }}"
  become: true
  become_user: root
  tags: mysql

- name: Configure MySQL
  template:
    src: "my.cnf.j2"
    dest: "{{ mysql_config_dir }}/my.cnf"
    mode: preserve
  become: true
  become_user: root
  notify: "Restart mysql"
  tags: mysql

- name: Check mysql service is running
  service:
    name: "{{ mysql_daemon }}"
    enabled: yes
    state: started
  tags: mysql

- name: Find temporary root password
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_root_password_temp
  when: mysql_root_password_update and ansible_os_family == "RedHat"
  tags: mysql

- debug:
    msg: "{{ mysql_root_password_temp.stdout }}"
  when: mysql_root_password_update and ansible_os_family == "RedHat"
  tags: mysql

- name: Set new root password
#  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -uroot'
  become: true
  become_user: root
  when: mysql_root_password_update
  tags: mysql

- name: Include SWEAGLE configuration.yml
  include_tasks: configure-sweagle.yml
  tags: [ mysql, sweagle, sweagle-mysql ]
