---
# Install MYSQL
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags: [mysql, sweagle, sweagle-mysql]

- name: Ensure MariaDB is not installed
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-libs
  become: true
  become_user: root
  tags: mysql

- name: Install the MySQL repo for Red Hat
  yum:
    name: "{{ mysql_repository }}"
    state: present
  when: ansible_os_family == "RedHat" and not force_local_installation
  become: true
  become_user: root
  tags: mysql

- name: Install MySQL packages from repo
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_packages }}"
  become: true
  become_user: root
  when: not force_local_installation
  tags: mysql

- name: Install MySQL packages for Debian from local
  apt:
    deb: "{{ item }}"
  with_items: "{{ lookup('fileglob', '../../../files/mysql/*.deb').split(',') | sort }}"
  become: true
  become_user: root
  when: ansible_os_family == "Debian" and force_local_installation
  tags: mysql

- name: Install MySQL packages for Red Hat from local
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lookup('fileglob', '../../../files/mysql/*.rpm').split(',') | sort }}"
  become: true
  become_user: root
  when: ansible_os_family == "RedHat" and force_local_installation
  tags: mysql

- name: Check mysql service is running
  service:
    name: "{{ mysql_daemon }}"
    enabled: yes
    state: started
  become: true
  become_user: root
  tags: mysql

- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false
  tags: mysql

- name: Include MySQL configuration.yml
  include_tasks: configure.yml
  tags: mysql

- name: Include SWEAGLE configuration.yml
  include_tasks: configure-sweagle.yml
  tags: [ mysql, sweagle, sweagle-mysql ]
