---
# Install MYSQL
- name: Create a group of hosts by ansible_distribution
  group_by: key={{ansible_distribution}}

- hosts: RedHat
  vars:
    mySQL_packages: [ mysql-server, mysql-client, mysql-common, python-mysqldb ]

- hosts: Debian
  vars:
    mySQL_packages:
      - mysql-server
      - mysql-client
      - mysql-common
      - python-mysqldb

- name: Install MySQL packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mySQL_packages }}"
  become: true
  become_user: root
  tags: mysql

#List of packages for CentOS
#    - mysql-community-server
#    - mysql-community-client
#    - MySQL-python

- name: Configure MySQL
  template:
    src: "my.cnf.j2"
    dest: "{{ mysql_config_dir }}/my.cnf"
    mode: preserve
  become: true
  become_user: root
  notify: "Restart mysql"
  tags: mysql

- name: Check mysql service is running
  service:
    name: mysql
    enabled: yes
    state: started
  tags: mysql

- name: Include SWEAGLE configuration.yml
  include: configure-sweagle.yml
  tags: [ mysql, sweagle, sweagle-mysql ]
