---
# file: dev servers
devservers:
  hosts:
    localhost:

webservers:
  hosts:
    localhost
    199.168.99.100

coreservers:
  hosts:
    localhost

vaultservers:
  hosts:
    localhost

scriptservers:
  hosts:
    localhost

dbservers:
  hosts:
    localhost

javaservers:
  children:
    coreservers
    vaultservers
    scriptservers
