---
- name: Install unzip
  package:
    name: unzip
    update_cache: yes
  become: true
  tags: vault

- name: Download and install vault binary
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /usr/bin/
    remote_src: True
  become: true
  tags: vault

- name: Create vault config directory
  file: state=directory path="{{ vault_conf_dir }}"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault config to server
  template:
    src: vaultconfig.hcl.j2
    dest: "{{ vault_conf_dir }}/vaultconfig.hcl"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault service to server
  template:
    src: vault.service.j2
    dest: "/usr/lib/systemd/system/vault.service"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Start vault service
  systemd:
    state: started
    name: vault
    daemon_reload: yes
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- pause:
    seconds: 15
  tags: vault

- name: Populate VAULT_ADDR in /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: true
  tags: vault

- name: Initialize the vault
  command: vault operator init
  register: keys
  environment:
    VAULT_ADDR: "http://127.0.0.1:{{ vault_port }}"
  become: true
  ignore_errors: true
  tags: vault
# for the moment, ignore if vault is already initialized
# in the future, test it before to init only if needed

- debug: msg="{{ keys }}"
  tags: vault

- name: Define file to store result of init
  set_fact: vault_key_file="{{ vault_conf_dir }}/keys-{{ ansible_date_time.iso8601_basic_short }}.txt"
  when: vault_copy_keys
  tags: vault

- name: Copy keys in "{{ vault_key_file }}"
  copy:
    content: "{{ keys }}"
    dest: "{{ vault_key_file }}"
  become: true
  when: vault_copy_keys
  tags: vault

- debug: msg="{{ vault_token }}"
  tags: vault

- name: Find init token
  shell: "echo `grep 'Initial Root Token: ' {{ vault_key_file }} | sed 's/.*Initial Root Token: '`"
  register: vault_token
  when: vault_token == ""
  tags: vault

- debug: msg="{{ vault_token }}"
  tags: vault
