---
- name: Install unzip
  package:
    name: unzip
    update_cache: yes
  become: true
  tags: vault

- name: Download and install vault binary
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /usr/bin/
    remote_src: True
  become: true
  tags: vault

- name: Create vault config directory
  file: state=directory path="{{ vault_conf_dir }}"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault config to server
  template:
    src: vaultconfig.hcl.j2
    dest: "{{ vault_conf_dir }}/vaultconfig.hcl"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault service to server
  template:
    src: vault.service.j2
    dest: "/usr/lib/systemd/system/vault.service"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Start vault service
  systemd:
    state: started
    name: vault
    daemon_reload: yes
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- pause:
    seconds: 10
  tags: [ vault, sweagle, sweagle-vault ]

- name: Populate VAULT_ADDR in /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: true
  tags: vault

- name: check if vault is already initialized
  command: "vault init -check -address=http://{{ sweagle_vault_server }}:{{ sweagle_vault_port }}"
  register: init_status
  ignore_errors: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Init made but no init token defined
  debug: msg="Vault has already been initialized, but no token provided. Please, enter token manually in SWEAGLE application.yml."
  when: init_status.rc == 0     # return code of 0 means init already done, cf. vault init --help
    and (vault_token is undefined or vault_token == "")
  tags: [ vault, sweagle, sweagle-vault ]

- name: Error on Vault
  debug: msg="Error on Vault, please correct after installation for encryption to work"
  when: init_status.rc == 1     # return code of 1 means error, cf. vault init --help
  tags: [ vault, sweagle, sweagle-vault ]

- name: Initialize Vault
  include_tasks: vault-init.yml
  when: init_status.rc == 2     # return code of 2 means not initialized, cf. vault init --help
  tags: [ vault, sweagle, sweagle-vault ]
