---
- name: Install unzip
  package:
    name: unzip
    update_cache: yes
  become: true
  tags: vault

- name: Download and install vault binary
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /usr/bin/
    remote_src: True
  become: true
  tags: vault

- name: Create vault config directory
  file: state=directory path="{{ vault_conf_dir }}"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault config to server
  template:
    src: vaultconfig.hcl.j2
    dest: "{{ vault_conf_dir }}/vaultconfig.hcl"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy vault service to server
  template:
    src: vault.service.j2
    dest: "/usr/lib/systemd/system/vault.service"
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- name: Start vault service
  systemd:
    state: started
    name: vault
    daemon_reload: yes
  become: true
  tags: [ vault, sweagle, sweagle-vault ]

- pause:
    seconds: 10
  tags: [ vault, sweagle, sweagle-vault ]

- name: Populate VAULT_ADDR in /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: true
  tags: vault

- name: check if vault is already initialized
  command: "vault init -check -address=http://{{ sweagle_vault_server }}:{{ sweagle_vault_port }}"
  register: init_status
  ignore_errors: true
  tags: vault

- name: Initialize the vault
  command: "vault init -address=http://{{ sweagle_vault_server }}:{{ sweagle_vault_port }}"
  register: keys
  when: init_status.rc == 2     # return code of 2 means not initialized, cf. vault init --help
  tags: vault

- name: Define file to store result of init
  set_fact: vault_key_file="{{ vault_conf_dir }}/keys-{{ ansible_date_time.iso8601_basic_short }}.txt"
  when: init_status.rc == 2 and vault_copy_keys
  tags: vault

- name: Copy keys in "{{ vault_key_file }}"
  copy:
    content: "{{ keys.stdout }}"
    dest: "{{ vault_key_file }}"
  become: true
  when: init_status.rc == 2 and vault_copy_keys
  tags: vault

- debug: msg="{{ vault_token }}"
  tags: vault

- name: Find init token
  set_fact:
    vault_token: "{{ keys.stdout_lines[5] | regex_replace('^Initial Root Token: (.*)$','\\1') }}"
  when: (vault_token is undefined or vault_token == "")
    and init_status.rc == 2
  tags: vault

#  shell: "echo `grep 'Initial Root Token: ' {{ vault_key_file }} | sed 's/.*Initial Root Token: //'`"
#- name: Find init token
#  register: vault_token
#  tags: vault

- debug: msg="Vault Init Token = {{ vault_token }}"
  tags: vault
