---
- name: Launch Vault init
  command: "{{ vault_install_dir }}/vault init -address=http://{{ inventory_hostname }}:{{ sweagle_vault_port }}"
  register: keys
  tags: [ vault, sweagle, sweagle-vault ]

- name: Define file to store result of init
  set_fact: vault_key_file="{{ vault_conf_dir }}/keys-{{ ansible_date_time.iso8601_basic_short }}.txt"
  when: vault_copy_keys
  tags: [ vault, sweagle, sweagle-vault ]

- name: Copy keys in "{{ vault_key_file }}"
  copy:
    content: "{{ keys.stdout }}"
    dest: "{{ vault_key_file }}"
  become: true
  when: vault_copy_keys
  tags: [ vault, sweagle, sweagle-vault ]

- name: Find init token and unseal keys
  set_fact:
    vault_key1: "{{ keys.stdout_lines[0] | regex_replace('^Unseal Key 1: (.*)$','\\1') }}"
    vault_key2: "{{ keys.stdout_lines[1] | regex_replace('^Unseal Key 2: (.*)$','\\1') }}"
    vault_key3: "{{ keys.stdout_lines[2] | regex_replace('^Unseal Key 3: (.*)$','\\1') }}"
    vault_token: "{{ keys.stdout_lines[5] | regex_replace('^Initial Root Token: (.*)$','\\1') }}"
  when: vault_token is undefined or vault_token == ""
  tags: [ vault, sweagle, sweagle-vault ]

- debug: msg="Vault Init Token = {{ vault_token }}"
  tags: [ vault, sweagle, sweagle-vault ]

#  shell: "echo `grep 'Initial Root Token: ' {{ vault_key_file }} | sed 's/.*Initial Root Token: //'`"
#- name: Find init token
#  register: vault_token
#  tags: vault

#- debug: msg="Vault Key 2 = {{ keys.stdout_lines[1] }}"
#  tags: [ vault, sweagle, sweagle-vault ]
