---

    - include: supercars_db_install.yml
      when: "inventory_hostname in groups.dbservers"

    - include: supercars_core_install.yml
      when: "inventory_hostname in groups.coreservers"

    - include: supercars_dev_install.yml
      when: "inventory_hostname in groups.devservers"
