---
sweagle_system_user: sweagle
sweagle_system_group: sweagle

sweagle_installation_folder: /opt/SWEAGLE/core
sweagle_core_port: 8081

sweagle_version:
sweagle_service_name: sweagle
sweagle_heap: 512m
sweagle_tenant: poc
sweagle_license_key:
