---
# file: production servers

[webservers]
localhost

[coreservers]
localhost

[vaultservers]
localhost

[scriptservers]
localhost

[dbservers]
localhost

[javaservers:children]
coreservers
vaultservers
scriptservers
