---
  # Install JDK
  - name: Install jdk 1.8
    package:
      name: openjdk-8-jdk
      state: present
    become: true
    become_user: root
    tags: jdk

  - name: Check Java version
    command: java -version
    register: java_version
    # Use the changed_when parameter so that this task doesn't appear as a changed status
    changed_when: false
    tags: jdk
