---
# Install JDK
- name: Install jdk 1.8 from local packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{% if ansible_os_family == 'Debian' %}{{ lookup('fileglob', '../../../files/jdk/*.deb').split(',') | sort }}
    {% else %}{{ lookup('fileglob', '../../../files/jdk/*.rpm').split(',') | sort }}{% endif %}"
  when: force_local_installation
  tags: jdk

- name: Install jdk 1.8 for Debian family
  package:
    name: openjdk-8-jdk
    state: present
  become: true
  when: force_local_installation == false and ansible_os_family == 'Debian'
  tags: jdk

- name: Install jdk 1.8 for Red Hat family
  package:
    name: java-1.8.0-openjdk
    state: present
  become: true
  when: force_local_installation == false and ansible_os_family == 'RedHat'
  tags: jdk

- name: Check Java version
  command: java -version
  register: java_version
  # Use the changed_when parameter so that this task doesn't appear as a changed status
  changed_when: false
  tags: jdk

- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  changed_when: False
  register: java_result
  tags: jdk

- name: Display Java version
  debug:
    msg: "{{ java_result }}"
  tags: jdk
