---
all:
  children:
    installserver:
      hosts:
        # Put only one host here this is the one used for tenant load script
        # It could be one of the appservers or webservers to avoid unzip of SWEAGLE package again
        localhost:
          ansible_connection: local
          #ansible_user: sweagle
          #ansible_password: sweagle
          #ansible_become_pass: root

    webservers:
      hosts:
        192.168.1.56:
          ansible_user: root
          ansible_password: root
          ansible_become_pass: root

    appservers:
      hosts:
        192.168.1.50:
          ansible_user: root
          ansible_password: root
          ansible_become_pass: root

    indexservers:
      hosts:
        192.168.1.56:
          ansible_user: sweagle
          ansible_password: sweagle
          ansible_become_pass: sweagle

    dbservers:
## If you want to install all DBs on same host, just uncomment hosts and comment children
## Don't forget to check that your play targets dbservers and not mysql + mongodb
#      hosts:
#        192.168.1.56:
#          ansible_user: sweagle
#          ansible_password: sweagle
#          ansible_become_pass: sweagle
      children:
        mysql:
          hosts:
            192.168.1.50:
              ansible_user: root
              ansible_password: root
              ansible_become_pass: root
        mongodb:
          hosts:
            192.168.1.56:
              ansible_user: sweagle
              ansible_password: sweagle
              ansible_become_pass: sweagle
