---
all:
  children:
    installserver:
      hosts:
        localhost:
          connection: local
          #ansible_user: sweagle
          #ansible_password: sweagle
          #ansible_become_pass: root

    webservers:
      hosts:
        192.168.1.49:
          connection: ssh
          ansible_user: sweagle
          ansible_password: sweagle
          ansible_ssh_port: 22
          ansible_become_pass: sweagle

    appservers:
      hosts:
        192.168.1.49:
          connection: ssh
          ansible_user: sweagle
          ansible_password: sweagle
          ansible_ssh_port: 22
          ansible_become_pass: sweagle

    indexservers:
      hosts:
        192.168.1.50:
          connection: ssh
          ansible_user: root
          ansible_password: root
          ansible_ssh_port: 22
          ansible_become_pass: root

    dbservers:
      hosts:
        192.168.1.50:
          connection: ssh
          ansible_user: root
          ansible_password: root
          ansible_ssh_port: 22
          ansible_become_pass: root
