---
all:
  children:
    installserver:
      hosts:
        # Put only one host here this is the one used for tenant load script
        localhost:
          ansible_connection: local
          #ansible_user: sweagle
          #ansible_password: sweagle
          #ansible_become_pass: root

    webservers:
      hosts:
        192.168.1.50:
          ansible_user: root
          ansible_password: root
          ansible_become_pass: root

    appservers:
      hosts:
        192.168.1.50:
          ansible_user: root
          ansible_password: root
          ansible_become_pass: root

    indexservers:
      hosts:
        192.168.1.56:
          ansible_user: sweagle
          ansible_password: sweagle
          ansible_become_pass: sweagle

    dbservers:
      hosts:
        192.168.1.56:
          ansible_user: sweagle
          ansible_password: sweagle
          ansible_become_pass: sweagle
