---
all-in-one:
  hosts:
    localhost

webservers:
  children:
    all-in-one

coreservers:
  children:
    all-in-one

vaultservers:
  children:
    all-in-one

[scriptservers:
  children:
    all-in-one

dbservers:
  children:
    all-in-one

javaservers:
  children:
    coreservers
    vaultservers
    scriptservers
