---
all:
  hosts:
    localhost
  children:

    webservers:
      hosts:
        localhost

    appservers:
      children:
        webservers:

    indexservers:
      children:
        webservers:

    dbservers:
      children:
        webservers:
