---
all:
  hosts:
    localhost


webservers:
  children:
    all

coreservers:
  children:
    all

vaultservers:
  children:
    all

scriptservers:
  children:
    all

dbservers:
  children:
    all

javaservers:
  children:
    coreservers
    vaultservers
    scriptservers
