---
all:
  children:
    installserver:
      hosts:
        localhost:
          ansible_connection: local
          #ansible_user: sweagle
          #ansible_password: sweagle
          #ansible_become_pass: sweagle

    webservers:
      children:
        installserver:

    appservers:
      children:
        installserver:

    indexservers:
      children:
        installserver:

    dbservers:
      children:
        mysql:
          children:
            installserver:
        mongodb:
          children:
            installserver:
