---
all:
  hosts:
    localhost

webservers:
  children:
    localhost

coreservers:
  children:
    webservers

vaultservers:
  children:
    webservers

scriptservers:
  children:
    webservers

dbservers:
  children:
    webservers

javaservers:
  children:
    coreservers
    vaultservers
    scriptservers
