---
all:
  hosts:
    localhost
  children:

    installserver:
      hosts:
        localhost

    webservers:
      children:
        installserver:

    appservers:
      children:
        installserver:

    indexservers:
      children:
        installserver:

    dbservers:
      children:
        installserver:
